<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body black-gray-container">
      
        <div class="d-flex justify-content-center">
          <img src="img/sucesso_cadastro.png"/>
        </div>

        <div class="row mt-5">
          <div class="col">
            <h1 class="title">Cadastro Realizado com Sucesso!</h1>
            <h2 class="subtitle">Agora você pode aproveitar sua nova conta Hover e se conectar com o mundo</h2>
          </div>
        </div>

        <div class="row mt-5">
          <div class="col">
            <a href="/HoverApp/public/" class="btn btn-green btn-block">Clique aqui para fazer login!</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  