<div class="container-fluid h-100 black-gray-container ">
    <div class="row h-100">
        <div class="col-md-6 banner d-none d-lg-block">
            <div class="row h-100 justify-content-center align-items-center">
                <div>
                    <div class="communicationItem">
                        <i class="fas fa-search fa-2x mr-3"></i>
                        Siga o que lhe interessa.
                    </div>
                    <div class="communicationItem">
                        <i class="fas fa-user-friends fa-2x mr-3"></i>
                        Saiba sobre o que as pessoas estão falando.
                    </div>
                    <div class="communicationItem">
                        <i class="far fa-comment fa-2x mr-3"></i>
                        Participe da conversa.
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 pt-4 pl-5 pr-5">
            <form method="POST" action="autenticar">
                <div class="row">
                    <div class="col">
                        <input type="text" name="email" class="form-control" placeholder="E-mail">
                    </div>
                    <div class="col password-container">
                        <input type="password" name="senha" class="form-control" placeholder="Senha" id="EntrarSenha">
                        <button type="button" id="togglePassword" class="toggle-password">
                            <i class="fa fa-eye"></i>
                        </button>
                    </div>
                    <div class="col-auto">
                        <button type="submit" class="btn btn-green mb-2">Entrar</button>
                    </div>

                </div>
                <div class="row">
                    <div class="col">
                    <?php if($this->view->login == "erro") {?>
                    <span class="text text-danger">Email e/ou Senha Inválidos</span>
                    <?php } ?>
                    </div>
                </div>
            </form>
            <div class="row pt-5 pl-5 pr-5">
                <div class="col pl-5 pr-5">
                    <img src="img/twitter_logo.png" width="120px" height="120px" />
                    <h1 class="title">Veja o que está acontecendo no mundo agora</h1>
                    <h2 class="mt-3 mb-4 subtitle">Participe hoje do Hover.</h2>
                    <a href="inscreverse" class="btn btn-green btn-block mb-2">Inscrever-se</a>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById('togglePassword').addEventListener('click', function (e) {
    const password = document.getElementById('EntrarSenha');
    const icon = e.target;

    // Alterna o tipo de input entre "password" e "text"
    if (password.type === 'password') {
        password.type = 'text';
        icon.classList.remove('fa-eye');
        icon.classList.add('fa-eye-slash');
    } else {
        password.type = 'password';
        icon.classList.remove('fa-eye-slash');
        icon.classList.add('fa-eye');
    }
});
</script>