<div class="container">
    <div class="d-flex justify-content-center mt-5">
        <div class="card" style="width: 36rem;">
            <div class="card-body black-gray-container">
                <div class="d-flex justify-content-center">
                    <img src="img/twitter_logo.png" />
                </div>
                <div class="row">
                    <div class="col">
                        <h2>Crie sua conta</h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                      <!-- Talvez tenha a / -->
                        <form action="registrar" method="post">
                            <div class="form-group">
                                <input type="text" value= "<?php $this->view->usuario['nome'] ?>"name="nome" class="form-control" placeholder="Nome">
                            </div>
                            <div class="form-group">
                                <input type="text" value= "<?php $this->view->usuario['email'] ?>" name="email" class="form-control" placeholder="E-mail">
                            </div>
                            <div class="form-group password-container">                            
                                <input type="password" value= "<?php $this->view->usuario['senha'] ?>" name="senha" class="form-control" placeholder="Senha" id="EntrarSenha">
                                <button type="button" id="togglePassword" class="toggle-password">
                                    <i class="fa fa-eye"></i>
                                </button>
                            </div>                
                            <div class="mt-4 mb-4">
                                <small class="form-text">
                                    Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                                </small>
                            </div>
                            <button type="submit" class="btn btn-green btn-block">Inscrever-se</button>

                            <?php if (isset($this->view->erroCadastro) && $this->view->erroCadastro) { ?>
                                <small class="form-text text-danger"> Erro ao Realizar o Cadastro, verifique se as informações foram inseridas corretamente</small>

                            <?php } else if (isset($this->view->erroEmailExistente) && $this->view->erroEmailExistente) { ?>
                                <small class="form-text text-danger"> Este e-mail já está cadastrado</small>

                            <?php } else if (isset($this->view->erroUsernameExistente) && $this->view->erroUsernameExistente) { ?>
                                <small class="form-text text-danger"> Este usuário já está cadastrado</small>

                            <?php } ?>

                        </form>

                        <div>
                            <i class="fas fa-angle-left"></i><a href="/HoverApp/public/" class="destaque"> Voltar</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    document.getElementById('togglePassword').addEventListener('click', function (e) {
    const password = document.getElementById('EntrarSenha');
    const icon = e.target;

    // Alterna o tipo de input entre "password" e "text"
    if (password.type === 'password') {
        password.type = 'text';
        icon.classList.remove('fa-eye');
        icon.classList.add('fa-eye-slash');
    } else {
        password.type = 'password';
        icon.classList.remove('fa-eye-slash');
        icon.classList.add('fa-eye');
    }
});
</script>